# permissions for end users to view consumergroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: konsumer-operator
    app.kubernetes.io/managed-by: kustomize
  name: consumergroup-viewer-role
rules:
- apiGroups:
  - github.com
  resources:
  - consumergroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github.com
  resources:
  - consumergroups/status
  verbs:
  - get
