---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - github.com
  resources:
  - consumergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.com
  resources:
  - consumergroups/finalizers
  verbs:
  - update
- apiGroups:
  - github.com
  resources:
  - consumergroups/status
  verbs:
  - get
  - patch
  - update
