apiVersion: github.com/v1alpha1
kind: ConsumerGroup
metadata:
  labels:
    app.kubernetes.io/name: konsumer-operator
    app.kubernetes.io/managed-by: kustomize
  name: consumergroup-sample
spec:
  refreshInterval: 30s
  groupId: test.group.001
  topic: test.topic
  minReplicas: 1
  maxReplicas: 24
  offsetThreshold: 10000
  containers:
    - name: consumer
      image: ghcr.io/flohansen/waiter
      args: ["-timeout", "1h"]

